public class Main {
    public static void main(String[] args)
    {
        String[][] language = new  String[][]
                { // {language name in english, hello world in that language}
                        {"English", "Hello World"}, {"Abkhaz", "Салам Адунеи"},
                        {"Acehnese", "Halo Donya"}, {"Acholi", "Apwoyo lobo"},
                        {"Afar", "Nagaale Baadal"}, {"Afrikaans", "Hallo Wêreld"},
                        {"Albanian", "Përshëndetje Botë"}, {"Alur", "Amothi ngom"},
                        {"Amharic", "ሰላም አለም"}, {"Arabic", "مرحبا بالعالم"},
                        {"Armenian", "Բարև աշխարհ"}, {"Assamese", "হেল্ল' ৱৰ্ল্ড"},
                        {"Avar", "Салам Дунял"}, {"Awadhi", "हैलो वर्ल्ड"},
                        {"Aymara", "Suma Uraqpachan"}, {"Azerbaijani", "Salam Dünya"},
                        {"Balinese", "Halo Jagat"}, {"Baluchi", "سلام دنیا"},
                        {"Bambara", "Bonjour Monde"}, {"Baoulé", "Bonjour Monde"},
                        {"Bashkir", "Һаумыһығыҙ Донъя"}, {"Basque", "Kaixo Mundua"},
                        {"Batak Karo", "Halo Dunia"}, {"Batak Simalungun", "Horas Dunia"},
                        {"Batak Toba", "Horas Dunia"}, {"Belarusian", "Прывітанне, свет"},
                        {"Bemba", "Mwapoleni Icalo conse"}, {"Bengali", "হ্যালো ওয়ার্ল্ড"},
                        {"Betawi", "Halo Dunia"}, {"Bhojpuri", "नमस्कार दुनिया के बा"},
                        {"Bikol", "Kumusta an Kinaban"}, {"Bosnian", "Zdravo svijete"},
                        {"Breton", "Salud Bed"}, {"Bulgarian", "Здравей, свят"},
                        {"Buryat", "Амар мэндэ Дэлхэй"}, {"Cantonese", "你好世界"},
                        {"Catalan", "Hola món"}, {"Cebuano", "Kumusta Kalibutan"},
                        {"Chamorro", "Håfa na Mundo"}, {"Chechen", "Салам маршал дуьне"},
                        {"Chichewa", "Moni Dziko Lapansi"}, {"Chinese (Simplified)", "你好世界"},
                        {"Chinese (Traditional)", "你好世界"}, {"Chuukese", "Kapong ngeni Fonufan"},
                        {"Chuvash", "Салам Тӗнче"}, {"Corsican", "Salutu u mondu"},
                        {"Crimean Tatar (Cyrillic)", "Селям алейкум Дюнья"}, {"Crimean Tatar (Latin)", "Selâm aleyküm Dünya"},
                        {"Croatian", "Pozdrav svijete"}, {"Czech", "Ahoj světe"},
                        {"Danish", "Hej Verden"}, {"Dari", "سلام جهان"},
                        {"Dhivehi", "ހެލޯ ވޯލްޑް"}, {"Dinka", "Muɔny Pinynhom"},
                        {"Dogri", "नमस्कार दुनिया"}, {"Dombe", "Wapona Nyika"},
                        {"Dutch", "Hallo wereld"}, {"Dyula", "Bonjour Duniɲa"},
                        {"Dzongkha", "ཧེ་ལོ་འཛམ་གླིང་།"}, {"Esperanto", "Saluton Mondo"},
                        {"Estonian", "Tere maailm"}, {"Ewe", "Mido gbe na Xexeame"},
                        {"Faroese", "Hey heimur"}, {"Fijian", "Saluton Mondo"},
                        {"Filipino", "Kumusta Mundo"}, {"Finnish", "Hei maailma"},
                        {"Fon", "Kudo Gbɛ ɔ"}, {"French", "Bonjour le monde"},
                        {"French (Canada)", "Salut tout le monde"}, {"Frisian", "Hallo wrâld"},
                        {"Friulian", "Ciao mont"}, {"Fulani", "On njaaraama Aduna"},
                        {"Ga", "Helo Jeŋ"}, {"Galician", "Ola Mundo"},
                        {"Georgian", "გამარჯობა მსოფლიო"}, {"German", "Hallo Welt"},
                        {"Greek", "Γεια σου κόσμε"}, {"Guarani", "Maitei Mundo"},
                        {"Gujarati", "હેલો વર્લ્ડ"}, {"Haitian Creole", "Bonjou Mond"},
                        {"Hakha Chin", "Hello Vawlei"}, {"Hausa", "Sannu Duniya"},
                        {"Hawaiian", "Aloha Honua"}, {"Hebrew", "שלום עולם"},
                        {"Hiligaynon", "Hello World"}, {"Hindi", "हैलो वर्ल्ड"},
                        {"Hmong", "Nyob Zoo Lub Ntiaj Teb"}, {"Hungarian", "Helló Világ"},
                        {"Hunsrik", "Hallo Welt"}, {"Iban", "Halo Dunya"},
                        {"Icelandic", "Halló heimur"}, {"Igbo", "Ndewo Ụwa"},
                        {"Ilocano", "Hello Lubong"}, {"Indonesian", "Halo Dunia"},
                        {"Inuktut (Latin)", "Haluu nunarjuaq"}, {"Inuktut (Syllabics)", "ᕼᐊᓘ ᓄᓇᕐᔪᐊᖅ"},
                        {"Irish", "Haigh a Dhomhanda"}, {"Italian", "Ciao mondo"},
                        {"Jamaican Patois", "Hello World"}, {"Japanese", "こんにちは世界"},
                        {"Javanese", "Halo Donya"}, {"Jingpo", "Hello Mungkan"},
                        {"Kalaallisut", "Hallo Verden"}, {"Kannada", "ಹಲೋ ವರ್ಲ್ಡ್"},
                        {"Kanuri", "Salam Dunya"}, {"Kapampangan", "Kamusta yatu"},
                        {"Kazakh", "Сәлем әлем"}, {"Khasi", "Khublei Pyrthei"},
                        {"Khmer", "សួស្តីពិភពលោក"}, {"Kiga", "Haro Ensi yoona"},
                        {"Kikongo", "Mbote Nsi-Ntoto"}, {"Kinyarwanda", "Muraho Isi"},
                        {"Kituba", "Mbote Inza"}, {"Kokborok", "Joto Swngchar"},
                        {"Komi", "Здравствуйте мир"}, {"Konkani", "हॅलो वर्ल्ड"},
                        {"Korean", "안녕하세요 세상아"}, {"Krio", "Halo Wɔl"},
                        {"Kurdish (Kurmanji)", "Silav Cîhan"}, {"Kurdish (Sorani)", "سڵاو جیهان"},
                        {"Kyrgyz", "Салам дүйнө"}, {"Lao", "ສະບາຍດີຊາວໂລກ"},
                        {"Latgalian", "Sveicīņs Pasauļam ."}, {"Latin", "Salve Mundus"},
                        {"Latvian", "Sveika, pasaule!"}, {"Ligurian", "Ciao Mondo"},
                        {"Limburgish", "Hallo Wereld"}, {"Lingala", "Mbote Mokili"},
                        {"Lithuanian", "Sveikas, pasauli"}, {"Lombard", "Ciao Mondo"},
                        {"Luganda", "Mwasuze mutya Ensi"}, {"Luo", "Mos Piny"},
                        {"Luxembourgish", "Moien Welt"}, {"Macedonian", "Здраво свете"},
                        {"Madurese", "Halo Dunnya"}, {"Maithili", "नमस्कार दुनिया"},
                        {"Makassar", "Hallo Dunia"}, {"Malagasy", "Hello World"},
                        {"Malay", "Halo Dunia"}, {"Malay (Jawi)", "سلام دنيا"},
                        {"Malayalam", "ഹലോ വേൾഡ്"}, {"Maltese", "Bongu Dinja"},
                        {"Mam", "B´a´n q´ij twitz tx´otx´"}, {"Manx", "Halloo yn Dooinney"},
                        {"Maori", "Kia ora te ao"}, {"Marathi", "हॅलो वर्ल्ड"},
                        {"Marshallese", "Yokwe lal in"}, {"Marwadi", "नमस्कार दुनिया"},
                        {"Mauritian Creole", "Bonzour Lemond"}, {"Meadow Mari", "Салам лийже Тӱня"},
                        {"Meiteilon (Manipuri)", "ꯍꯦꯂꯣ ꯋꯥꯔꯜꯗ꯫"}, {"Minang", "Halo Dunia"},
                        {"Mizo", "Hello Khawvel"}, {"Mongolian", "Сайн уу Дэлхий"},
                        {"Myanmar (Burmese)", "မင်္ဂလာပါကမ္ဘာလောက"}, {"Nahuatl (Eastern Huasteca)", "Kuali kajki Tlaltipaktli"},
                        {"Ndau", "Kwazuwai Nyika"}, {"Ndebele (South)", "Sawubona iphasi"},
                        {"Nepalbhasa (Newari)", "ज्वजलपा हलिं"}, {"Nepali", "नमस्ते संसार"},
                        {"NKo", "ߊߟߎ߫ ߣߌ߫ ߖߐ߫ ߘߎߢߊ߫"}, {"Norwegian", "Hallo verden"},
                        {"Nuer", "Ɣëlö Wecmuɔ̱ɔ̱n"}, {"Occitan", "Adieu Mond"},
                        {"Odia (Oriya)", "ନମସ୍କାର ବିଶ୍ୱ"}, {"Oromo", "Akkam jirtu Addunyaa"},
                        {"Ossetian", "Салам Дуне"}, {"Pangasinan", "Hello World"},
                        {"Papiamento", "Hola Mundu"}, {"Pashto", "سلام نړی"},
                        {"Persian", "سلام دنیا"}, {"Polish", "Witaj świecie"},
                        {"Portuguese (Brazil)", "Olá Mundo"}, {"Portuguese (Portugal)", "Olá, mundo!"},
                        {"Punjabi (Gurmukhi)", "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ"}, {"Punjabi (Shahmukhi)", "ہیلو ورلڈ"},
                        {"Quechua", "Allinllachu Mundo"}, {"Qʼeqchiʼ", "Chaab'il eere li Ruchich'och'"},
                        {"Romani", "Bachtalo Luma"}, {"Romanian", "Salut Lume"},
                        {"Rundi", "Muraho Isi"}, {"Russian", "Привет, мир"},
                        {"Sami (North)", "Hei máilbmi"}, {"Samoan", "Talofa Lalolagi"},
                        {"Sango", "Bonjour Monde"}, {"Sanskrit", "नमस्कार विश्व"},
                        {"Santali (Latin)", "Johar Duniya"}, {"Santali (Ol Chiki)", "ᱡᱚᱦᱟᱨ ᱡᱮᱜᱮᱛ"},
                        {"Scots Gaelic", "Halò an t-Saoghail"}, {"Sepedi", "Thobela Lefase"},
                        {"Serbian", "Здраво свете"}, {"Sesotho", "Lefatše Lumela"},
                        {"Seychellois Creole", "Bonzour Lemonn"}, {"Shan", "မႂ်ႇသုင်လုမ်ႈၾႃႉ"},
                        {"Shona", "Mhoro Nyika"}, {"Sicilian", "Ciao Munnu"},
                        {"Silesian", "Witaj Świat"}, {"Sindhi", "هيلو ورلڊ"},
                        {"Sinhala", "හෙලෝ වර්ල්ඩ්"}, {"Slovak", "Ahoj svet"},
                        {"Slovenian", "Pozdravljen svet"}, {"Somali", "Salaan Adduun"},
                        {"Spanish", "Hola Mundo"}, {"Sundanese", "Halo Dunya"},
                        {"Susu", "DuniE wo xa sEwa"}, {"Swahili", "Habari Dunia"},
                        {"Swati", "Sawubona Umhlaba"}, {"Swedish", "Hej världen"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                        {"BLAH", "BLAH"}, {"BLAH", "BLAH"},
                };
    }
}